# Generated by Django 5.2.5 on 2025-08-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_customuser_is_driver_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ride_block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
