# Generated by Django 5.2.5 on 2025-08-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.FloatField(default=12.345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.FloatField(default=12.345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(default=12.345678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(default=12.345678),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
